jekyll:
    image: jekyll/jekyll:builder
    command: jekyll serve --watch --incremental --force_polling --livereload
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - .:/srv/jekyll